routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes(['register' => true]);

// Links Painel Admin
Route::group([
    'middleware' => 'auth',
    'prefix' => 'admin',
    'namespace' => 'Admin'], function() {

    // Listar Inativos
    Route::get('/almoxarifado/arquivado', 'WarehouseController@deleted')->name('admin.almoxarifado.deleted');
    Route::get('/fornecedor/arquivado', 'ProviderController@deleted')->name('admin.fornecedor.deleted');
    Route::get('/funcionario/arquivado', 'EmployeeController@deleted')->name('admin.funcionario.deleted');
    Route::get('/ferramenta/arquivado', 'ToolController@deleted')->name('admin.ferramenta.deleted');
    Route::get('/obra/arquivado', 'BuildingController@deleted')->name('admin.obra.deleted');
    Route::get('/setor/arquivado', 'SectorController@deleted')->name('admin.setor.deleted');
    Route::get('/funcao/arquivado', 'OfficeController@deleted')->name('admin.funcao.deleted');
    Route::get('/unidade/arquivado', 'UnityController@deleted')->name('admin.unidade.deleted');
    Route::get('/tipoitem/arquivado', 'ItemTypeController@deleted')->name('admin.tipoitem.deleted');
    Route::get('/tipoentrada/arquivado', 'ItemTypeController@deleted')->name('admin.tipoentrada.deleted');
    Route::get('/entrada/arquivado', 'EntranceController@deleted')->name('admin.entrada.deleted');
    Route::get('/retirada/arquivado', 'WithdrawalController@deleted')->name('admin.retirada.deleted');

    // Restaurar Inativos
    Route::post('/almoxarifado/restore/{id}', 'WarehouseController@restore')->name('admin.almoxarifado.restore');
    Route::post('/fornecedor/restore/{id}', 'ProviderController@restore')->name('admin.fornecedor.restore');
    Route::post('/funcionario/restore/{id}', 'EmployeeController@restore')->name('admin.funcionario.restore');
    Route::post('/ferramenta/restore/{id}', 'ToolController@restore')->name('admin.ferramenta.restore');
    Route::post('/obra/restore/{id}', 'BuildingController@restore')->name('admin.obra.restore');
    Route::post('/setor/restore/{id}', 'SectorController@restore')->name('admin.setor.restore');
    Route::post('/funcao/restore/{id}', 'OfficeController@restore')->name('admin.funcao.restore');
    Route::post('/unidade/restore/{id}', 'UnityController@restore')->name('admin.unidade.restore');
    Route::post('/tipoitem/restore/{id}', 'ItemTypeController@restore')->name('admin.tipoitem.restore');
    Route::post('/tipoentrada/restore/{id}', 'EntranceTypeController@restore')->name('admin.tipoentrada.restore');
    Route::post('/entrada/restore/{id}', 'EntranceController@restore')->name('admin.entrada.restore');
    Route::post('/retirada/restore/{id}', 'WithdrawalController@restore')->name('admin.retirada.restore');

    Route::get('/funcionario/usuario/{id}', 'EmployeeController@userEdit')->name('admin.funcionario.user.edit');
    Route::patch('/funcionario/usuario/{id}', 'EmployeeController@userUpdate')->name('admin.funcionario.user.update');

    // Resources
    Route::resource('fornecedor', 'ProviderController', ['as' => 'admin']);
    Route::resource('almoxarifado', 'WarehouseController', ['as' => 'admin']);
    Route::resource('funcionario', 'EmployeeController', ['as' => 'admin']);
    Route::resource('obra', 'BuildingController', ['as' => 'admin']);
    Route::resource('ferramenta', 'ToolController', ['as' => 'admin']);
    Route::resource('entrada', 'EntranceController', ['as' => 'admin']);
    Route::resource('retirada', 'WithdrawalController', ['as' => 'admin']);
    Route::resource('setor', 'SectorController', ['as' => 'admin']);
    Route::resource('funcao', 'OfficeController', ['as' => 'admin']);
    Route::resource('unidade', 'UnityController', ['as' => 'admin']);
    Route::resource('tipoitem', 'ItemTypeController', ['as' => 'admin']);
    Route::resource('tipoentrada', 'EntranceTypeController', ['as' => 'admin']);
    Route::resource('usuario', 'UserController', ['as' => 'admin']);
    Route::resource('fatura', 'InvoiceController', ['as' =>'admin']);
    Route::resource('transferencia', 'TransferController', ['as' =>'admin']);
    Route::resource('estoque', 'InventoryController', ['as' => 'admin']);


    Route::get('/usuarios', 'UserController@index')->name('admin.user.index');

    Route::get('/ferramentas/datatables.json', 'ToolController@datatablesAjax')->name('admin.ferramenta.datatables');

    Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard.index');

    Route::post('/transferencia/cancel/{id}', 'TransferController@cancel')->name('admin.transferencia.cancel');

    Route::post('/import/{type}', 'ImportController@import')->name('admin.import.submit');
});

Route::group([
    'middleware' => 'auth',
    'prefix' => 'user',
    'namespace' => 'User'], function() {

    // Listar Inativos
    Route::get('/almoxarifado/arquivado', 'WarehouseController@deleted')->name('user.almoxarifado.deleted');
    Route::get('/fornecedor/arquivado', 'ProviderController@deleted')->name('user.fornecedor.deleted');
    Route::get('/funcionario/arquivado', 'EmployeeController@deleted')->name('user.funcionario.deleted');
    Route::get('/ferramenta/arquivado', 'ToolController@deleted')->name('user.ferramenta.deleted');
    Route::get('/obra/arquivado', 'BuildingController@deleted')->name('user.obra.deleted');
    Route::get('/setor/arquivado', 'SectorController@deleted')->name('user.setor.deleted');
    Route::get('/funcao/arquivado', 'OfficeController@deleted')->name('user.funcao.deleted');
    Route::get('/unidade/arquivado', 'UnityController@deleted')->name('user.unidade.deleted');
    Route::get('/tipoitem/arquivado', 'ItemTypeController@deleted')->name('user.tipoitem.deleted');
    Route::get('/tipoentrada/arquivado', 'ItemTypeController@deleted')->name('user.tipoentrada.deleted');

    // Restaurar Inativos
    Route::post('/almoxarifado/restore/{id}', 'WarehouseController@restore')->name('user.almoxarifado.restore');
    Route::post('/fornecedor/restore/{id}', 'ProviderController@restore')->name('user.fornecedor.restore');
    Route::post('/funcionario/restore/{id}', 'EmployeeController@restore')->name('user.funcionario.restore');
    Route::post('/ferramenta/restore/{id}', 'ToolController@restore')->name('user.ferramenta.restore');
    Route::post('/obra/restore/{id}', 'BuildingController@restore')->name('user.obra.restore');
    Route::post('/setor/restore/{id}', 'SectorController@restore')->name('user.setor.restore');
    Route::post('/funcao/restore/{id}', 'OfficeController@restore')->name('user.funcao.restore');
    Route::post('/unidade/restore/{id}', 'UnityController@restore')->name('user.unidade.restore');
    Route::post('/tipoitem/restore/{id}', 'ItemTypeController@restore')->name('user.tipoitem.restore');
    Route::post('/tipoentrada/restore/{id}', 'EntranceTypeController@restore')->name('user.tipoentrada.restore');

    Route::get('/funcionario/usuario/{id}', 'EmployeeController@userEdit')->name('user.funcionario.user.edit');
    Route::patch('/funcionario/usuario/{id}', 'EmployeeController@userUpdate')->name('user.funcionario.user.update');

    // Resources
    Route::resource('fornecedor', 'ProviderController', ['as' => 'user']);
    Route::resource('almoxarifado', 'WarehouseController', ['as' => 'user']);
    Route::resource('funcionario', 'EmployeeController', ['as' => 'user']);
    Route::resource('obra', 'BuildingController', ['as' => 'user']);
    Route::resource('ferramenta', 'ToolController', ['as' => 'user']);
    Route::resource('entrada', 'EntranceController', ['as' => 'user']);
    Route::resource('retirada', 'WithdrawalController', ['as' => 'user']);
    Route::resource('setor', 'SectorController', ['as' => 'user']);
    Route::resource('funcao', 'OfficeController', ['as' => 'user']);
    Route::resource('unidade', 'UnityController', ['as' => 'user']);
    Route::resource('tipoitem', 'ItemTypeController', ['as' => 'user']);
    Route::resource('tipoentrada', 'EntranceTypeController', ['as' => 'user']);

    Route::get('/usuarios', 'UserController@index')->name('user.user.index');
    Route::post('/retirada/{id}/cancel', 'WithdrawalController@cancel')->name('user.retirada.cancel');
    Route::post('/retirada/{id}/approve', 'WithdrawalController@approve')->name('user.retirada.approve');
    Route::post('/retirada/{id}/giveback', 'WithdrawalController@giveback')->name('user.retirada.giveback');

    Route::get('/profile', 'UserController@profile')->name('user.profile');

    Route::get('/dashboard', 'DashboardController@index')->name('user.dashboard.index');
});

Route::post('/reportbug', 'ReportController@report')->name('reportbug');

app/Models/Sector.php
<?php

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;
use OwenIt\Auditing\Contracts\Auditable;

class Sector extends Eloquent
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name'
    ];

    public function employees()
    {
        return $this->hasMany(Employee::class)->withTrashed();
    }
}

app/Http/Controllers/Admin/SectorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreSector;
use App\Http\Requests\UpdateSector;
use App\Models\Sector;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class SectorController extends Controller
{/**
 * Display a listing of the resource.
 *
 * @return \Illuminate\Http\Response
 */
    public function index()
    {
        $expiration = 60 * 60 *24;
        $key = 'sectors';

        $sectors = Cache::remember($key, $expiration, function () {
            return  Sector::all();
        });

        return view('admin.sector.index',compact('sectors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.sector.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSector $request)
    {
        $validated = $request->validated();

        $sector = new Sector($validated);
        $sector->save();

        return redirect('/admin/setor')->with('success', 'Novo setor adicionado.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Sector  $sector
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $sector = Sector::withTrashed()->find($id);

        return view('admin.sector.show',compact('sector'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sector  $sector
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sector = Sector::withTrashed()->find($id);

        return view('admin.sector.edit',compact('sector'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Sector  $sector
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSector $request, $id)
    {
        $validated = $request->validated();

        $sector = Sector::find($id);
        //$sector->doc = $request->get('doc');
        $sector->name = $request->get('name');
        $sector->save();

        return redirect('/admin/setor')->with('success', 'Setor editado.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sector  $sector
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sector = Sector::find($id);
        $sector->delete();

        return redirect('/admin/setor')->with('success', 'Setor deletado.');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        $sector = Sector::withTrashed()->find($id);
        $sector->restore();

        return redirect('/admin/setor')->with('success', 'Setor restaurado.');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function deleted()
    {
        $sectors = Sector::onlyTrashed()->get();

        return view('admin.sector.deleted',compact('sectors'));
    }
}

app/Http/Controllers/User/SectorController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Requests\StoreSector;
use App\Http\Requests\UpdateSector;
use App\Models\Sector;
use Illuminate\Http\Request;

class SectorController extends Controller
{/**
 * Display a listing of the resource.
 *
 * @return \Illuminate\Http\Response
 */
    public function index()
    {
        $sectors = Sector::all();

        return view('user.sector.index',compact('sectors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.sector.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSector $request)
    {
        $validated = $request->validated();

        $sector = new Sector($validated);
        $sector->save();

        return redirect('/user/setor')->with('success', 'Novo setor adicionado.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Sector  $sector
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $sector = Sector::withTrashed()->find($id);

        return view('user.sector.show',compact('sector'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sector  $sector
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sector = Sector::withTrashed()->find($id);

        return view('user.sector.edit',compact('sector'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Sector  $sector
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSector $request, $id)
    {
        $validated = $request->validated();

        $sector = Sector::find($id);
        //$sector->doc = $request->get('doc');
        $sector->name = $request->get('name');
        $sector->save();

        return redirect('/user/setor')->with('success', 'Setor editado.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sector  $sector
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sector = Sector::find($id);
        $sector->delete();

        return redirect('/user/setor')->with('success', 'Setor deletado.');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        $sector = Sector::withTrashed()->find($id);
        $sector->restore();

        return redirect('/user/setor')->with('success', 'Setor restaurado.');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function deleted()
    {
        $sectors = Sector::onlyTrashed()->get();

        return view('user.sector.deleted',compact('sectors'));
    }
}

resources/views/admin/sector/index.blade.php
@extends('layouts.app')

@section('page-header')
    <div class="page-title">

        <div class="pull-left">
            <!-- PAGE HEADING TAG - START --><h1 class="title">Setores</h1><!-- PAGE HEADING TAG - END -->                            </div>

        <div class="pull-right hidden-xs">
            <ol class="breadcrumb">
                <li>
                    <a href="/"><i class="fa fa-home"></i>Home</a>
                </li>
                <li class="active">
                    <strong>Setores</strong>
                </li>
            </ol>
        </div>

    </div>
@endsection

@section('content')
    <div class="col-lg-12">
        <section class="box ">
            <header class="panel_header">
                <h2 class="title pull-left">Todos os Setores</h2>
                <div class="actions panel_actions pull-right">
                    <a href="{{ route("admin.setor.create") }}">
                        <button type="button" class="btn btn-primary btn-icon btn-sm">
                            <i class="fa fa-plus"></i> &nbsp; <span>Adicionar</span>
                        </button>
                    </a>
                </div>
            </header>
            <div class="content-body">
                <div class="row">
                    @if(session()->get('success'))
                        <div class="alert alert-success alert-dismissible fade in">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                            <strong>Sucesso!</strong> {{ session()->get('success') }}
                        </div>
                    @endif
                    <div class="col-xs-12">

                        <table class="table datatable display responsive no-wrap" width="100%">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Opções</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($sectors as $sector)
                                <tr>
                                    <td>{{ $sector->name }}</td>
                                    <td>
                                        <ul class="list-inline">
                                            <li>
                                                <a href="{{ route("admin.setor.show", $sector->id) }}">
                                                    <button class="btn btn-sm btn-info" title="Visualizar Setor">
                                                        <span class="fa fa-eye"></span>
                                                    </button>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{{ route("admin.setor.edit", $sector->id) }}">
                                                    <button class="btn btn-sm btn-accent" title="Editar Setor">
                                                        <span class="fa fa-edit"></span>
                                                    </button>
                                                </a>
                                            </li>
                                            <li>
                                                <form action="{{ route('admin.setor.destroy', $sector->id)}}" method="post">
                                                    @csrf
                                                    <meta name="_token" content="{{ csrf_token() }}">
                                                    @method('DELETE')
                                                    <button class="btn btn-sm btn-danger" title="Desativar Setor"
                                                            data-toggle="confirm"
                                                            data-title=""
                                                            data-message="Tem certeza que deseja desativar esse setor?"
                                                            data-type="danger">
                                                        <span class="fa fa-trash"></span>
                                                    </button>
                                                </form>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@section('post_scripts')
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css"/>
    <script src="/assets/plugins/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/Responsive/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
    <script>
        $(document).ready( function () {
            $('.datatable').dataTable({
                responsive: true,
                "language": {
                    "url": "/assets/js/datatables-1.10.18/Portuguese-Brasil.json"
                }
            });
        } );
    </script>
@endsection

resources/views/admin/sector/show.blade.php
@extends('layouts.app')

@section('page-header')
    <div class="page-title">

        <div class="pull-left">
            <!-- PAGE HEADING TAG - START --><h1 class="title">Setores</h1><!-- PAGE HEADING TAG - END -->                            </div>

        <div class="pull-right hidden-xs">
            <ol class="breadcrumb">
                <li>
                    <a href="/"><i class="fa fa-home"></i>Home</a>
                </li>
                <li class="active">
                    <strong>Visualizar Setor</strong>
                </li>
            </ol>
        </div>

    </div>
@endsection

@section('content')
    <div class="col-lg-12">
        <section class="box ">
            <header class="panel_header">
                <h2 class="title pull-left">Visualizar Setor</h2>
                <div class="actions panel_actions pull-right">
                    <a class="box_toggle fa fa-chevron-down"></a>
                </div>
            </header>
            <div class="content-body">    <div class="row">
                    <div class="col-xs-12">

                        <div class="row">
                            <div class="col-md-4 col-sm-5 col-xs-10">

                                <div class="form-group">
                                    <label class="form-label" for="field-1">Nome</label>
                                    <div class="controls">
                                        <input type="text" class="form-control" name="name" value="{{ $sector->name }}" readonly disabled >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="controls">
                                        <button class="btn btn-primary" onclick="history.back(-1)">Voltar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div class="col-lg-12">
        <section class="box ">
            <header class="panel_header">
                <h2 class="title pull-left">Visualizar Funcionários</h2>
                <div class="actions panel_actions pull-right">
                    <a class="box_toggle fa fa-chevron-down"></a>
                </div>
            </header>
            <div class="content-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="row">

                            <table class="table datatable display responsive no-wrap" width="100%">
                                <thead>
                                <tr>
                                    <th>CPF</th>
                                    <th>Nome</th>
                                    <th>Função</th>
                                    <th>Setor</th>
                                    <th>Obra</th>
                                    <th>Usuário</th>
                                    <th>Contato</th>
                                    <th>Opções</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($sector->employees as $employee)
                                    <tr>
                                        <td>{{ $employee->doc }}</td>
                                        <td>{{ $employee->name }}</td>
                                        <td>{{ $employee->office['name'] }}</td>
                                        <td>{{ $employee->sector['name'] }}</td>
                                        <td>
                                            @if($employee->building != null)
                                            <a href="{{ route("admin.obra.show", $employee->building["id"]) }}">
                                                {{ $employee->building['name'] }}
                                            </a>
                                            @else
                                                Sem Obra Definida
                                            @endif
                                        </td>
                                        <td>{{ $employee->user['username'] }}</td>
                                        <td>{{ $employee->contact }}</td>
                                        <td>
                                            <ul class="list-inline">
                                                <li>
                                                    <a href="{{ route("admin.funcionario.show", $employee->id) }}">
                                                        <button class="btn btn-sm btn-info" title="Visualizar Funcionário">
                                                            <span class="fa fa-eye"></span>
                                                        </button>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="{{ route("admin.funcionario.edit", $employee->id) }}">
                                                        <button class="btn btn-sm btn-accent" title="Editar Funcionário">
                                                            <span class="fa fa-edit"></span>
                                                        </button>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="{{ route("admin.funcionario.user.edit", $employee->id) }}">
                                                        <button class="btn btn-sm btn-success" title="Adcionar/Editar Usuário">
                                                            <span class="fa fa-user"></span>
                                                        </button>
                                                    </a>
                                                </li>
                                                <li>
                                                    <form action="{{ route('admin.funcionario.destroy', $employee->id)}}" method="post">
                                                        @csrf
                                                        <meta name="_token" content="{{ csrf_token() }}">
                                                        @method('DELETE')
                                                        <button class="btn btn-sm btn-danger" title="Desativar Funcionário"
                                                                data-toggle="confirm"
                                                                data-title=""
                                                                data-message="Tem certeza que deseja desativar esse funcionário?"
                                                                data-type="danger">
                                                            <span class="fa fa-trash"></span>
                                                        </button>
                                                    </form>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@section('post_scripts')
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css"/>
    <script src="/assets/plugins/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/Responsive/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
    <script>
        $(document).ready( function () {
            $('.datatable').dataTable({
                responsive: true,
                "language": {
                    "url": "/assets/js/datatables-1.10.18/Portuguese-Brasil.json"
                }
            });
        } );
    </script>
@endsection