routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes(['register' => true]);

// Links Painel Admin
Route::group([
    'middleware' => 'auth',
    'prefix' => 'admin',
    'namespace' => 'Admin'], function() {

    // Listar Inativos
    Route::get('/almoxarifado/arquivado', 'WarehouseController@deleted')->name('admin.almoxarifado.deleted');
    Route::get('/fornecedor/arquivado', 'ProviderController@deleted')->name('admin.fornecedor.deleted');
    Route::get('/funcionario/arquivado', 'EmployeeController@deleted')->name('admin.funcionario.deleted');
    Route::get('/ferramenta/arquivado', 'ToolController@deleted')->name('admin.ferramenta.deleted');
    Route::get('/obra/arquivado', 'BuildingController@deleted')->name('admin.obra.deleted');
    Route::get('/setor/arquivado', 'SectorController@deleted')->name('admin.setor.deleted');
    Route::get('/funcao/arquivado', 'OfficeController@deleted')->name('admin.funcao.deleted');
    Route::get('/unidade/arquivado', 'UnityController@deleted')->name('admin.unidade.deleted');
    Route::get('/tipoitem/arquivado', 'ItemTypeController@deleted')->name('admin.tipoitem.deleted');
    Route::get('/tipoentrada/arquivado', 'ItemTypeController@deleted')->name('admin.tipoentrada.deleted');
    Route::get('/entrada/arquivado', 'EntranceController@deleted')->name('admin.entrada.deleted');
    Route::get('/retirada/arquivado', 'WithdrawalController@deleted')->name('admin.retirada.deleted');

    // Restaurar Inativos
    Route::post('/almoxarifado/restore/{id}', 'WarehouseController@restore')->name('admin.almoxarifado.restore');
    Route::post('/fornecedor/restore/{id}', 'ProviderController@restore')->name('admin.fornecedor.restore');
    Route::post('/funcionario/restore/{id}', 'EmployeeController@restore')->name('admin.funcionario.restore');
    Route::post('/ferramenta/restore/{id}', 'ToolController@restore')->name('admin.ferramenta.restore');
    Route::post('/obra/restore/{id}', 'BuildingController@restore')->name('admin.obra.restore');
    Route::post('/setor/restore/{id}', 'SectorController@restore')->name('admin.setor.restore');
    Route::post('/funcao/restore/{id}', 'OfficeController@restore')->name('admin.funcao.restore');
    Route::post('/unidade/restore/{id}', 'UnityController@restore')->name('admin.unidade.restore');
    Route::post('/tipoitem/restore/{id}', 'ItemTypeController@restore')->name('admin.tipoitem.restore');
    Route::post('/tipoentrada/restore/{id}', 'EntranceTypeController@restore')->name('admin.tipoentrada.restore');
    Route::post('/entrada/restore/{id}', 'EntranceController@restore')->name('admin.entrada.restore');
    Route::post('/retirada/restore/{id}', 'WithdrawalController@restore')->name('admin.retirada.restore');

    Route::get('/funcionario/usuario/{id}', 'EmployeeController@userEdit')->name('admin.funcionario.user.edit');
    Route::patch('/funcionario/usuario/{id}', 'EmployeeController@userUpdate')->name('admin.funcionario.user.update');

    // Resources
    Route::resource('fornecedor', 'ProviderController', ['as' => 'admin']);
    Route::resource('almoxarifado', 'WarehouseController', ['as' => 'admin']);
    Route::resource('funcionario', 'EmployeeController', ['as' => 'admin']);
    Route::resource('obra', 'BuildingController', ['as' => 'admin']);
    Route::resource('ferramenta', 'ToolController', ['as' => 'admin']);
    Route::resource('entrada', 'EntranceController', ['as' => 'admin']);
    Route::resource('retirada', 'WithdrawalController', ['as' => 'admin']);
    Route::resource('setor', 'SectorController', ['as' => 'admin']);
    Route::resource('funcao', 'OfficeController', ['as' => 'admin']);
    Route::resource('unidade', 'UnityController', ['as' => 'admin']);
    Route::resource('tipoitem', 'ItemTypeController', ['as' => 'admin']);
    Route::resource('tipoentrada', 'EntranceTypeController', ['as' => 'admin']);
    Route::resource('usuario', 'UserController', ['as' => 'admin']);
    Route::resource('fatura', 'InvoiceController', ['as' =>'admin']);
    Route::resource('transferencia', 'TransferController', ['as' =>'admin']);
    Route::resource('estoque', 'InventoryController', ['as' => 'admin']);


    Route::get('/usuarios', 'UserController@index')->name('admin.user.index');

    Route::get('/ferramentas/datatables.json', 'ToolController@datatablesAjax')->name('admin.ferramenta.datatables');

    Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard.index');

    Route::post('/transferencia/cancel/{id}', 'TransferController@cancel')->name('admin.transferencia.cancel');

    Route::post('/import/{type}', 'ImportController@import')->name('admin.import.submit');
});

Route::group([
    'middleware' => 'auth',
    'prefix' => 'user',
    'namespace' => 'User'], function() {

    // Listar Inativos
    Route::get('/almoxarifado/arquivado', 'WarehouseController@deleted')->name('user.almoxarifado.deleted');
    Route::get('/fornecedor/arquivado', 'ProviderController@deleted')->name('user.fornecedor.deleted');
    Route::get('/funcionario/arquivado', 'EmployeeController@deleted')->name('user.funcionario.deleted');
    Route::get('/ferramenta/arquivado', 'ToolController@deleted')->name('user.ferramenta.deleted');
    Route::get('/obra/arquivado', 'BuildingController@deleted')->name('user.obra.deleted');
    Route::get('/setor/arquivado', 'SectorController@deleted')->name('user.setor.deleted');
    Route::get('/funcao/arquivado', 'OfficeController@deleted')->name('user.funcao.deleted');
    Route::get('/unidade/arquivado', 'UnityController@deleted')->name('user.unidade.deleted');
    Route::get('/tipoitem/arquivado', 'ItemTypeController@deleted')->name('user.tipoitem.deleted');
    Route::get('/tipoentrada/arquivado', 'ItemTypeController@deleted')->name('user.tipoentrada.deleted');

    // Restaurar Inativos
    Route::post('/almoxarifado/restore/{id}', 'WarehouseController@restore')->name('user.almoxarifado.restore');
    Route::post('/fornecedor/restore/{id}', 'ProviderController@restore')->name('user.fornecedor.restore');
    Route::post('/funcionario/restore/{id}', 'EmployeeController@restore')->name('user.funcionario.restore');
    Route::post('/ferramenta/restore/{id}', 'ToolController@restore')->name('user.ferramenta.restore');
    Route::post('/obra/restore/{id}', 'BuildingController@restore')->name('user.obra.restore');
    Route::post('/setor/restore/{id}', 'SectorController@restore')->name('user.setor.restore');
    Route::post('/funcao/restore/{id}', 'OfficeController@restore')->name('user.funcao.restore');
    Route::post('/unidade/restore/{id}', 'UnityController@restore')->name('user.unidade.restore');
    Route::post('/tipoitem/restore/{id}', 'ItemTypeController@restore')->name('user.tipoitem.restore');
    Route::post('/tipoentrada/restore/{id}', 'EntranceTypeController@restore')->name('user.tipoentrada.restore');

    Route::get('/funcionario/usuario/{id}', 'EmployeeController@userEdit')->name('user.funcionario.user.edit');
    Route::patch('/funcionario/usuario/{id}', 'EmployeeController@userUpdate')->name('user.funcionario.user.update');

    // Resources
    Route::resource('fornecedor', 'ProviderController', ['as' => 'user']);
    Route::resource('almoxarifado', 'WarehouseController', ['as' => 'user']);
    Route::resource('funcionario', 'EmployeeController', ['as' => 'user']);
    Route::resource('obra', 'BuildingController', ['as' => 'user']);
    Route::resource('ferramenta', 'ToolController', ['as' => 'user']);
    Route::resource('entrada', 'EntranceController', ['as' => 'user']);
    Route::resource('retirada', 'WithdrawalController', ['as' => 'user']);
    Route::resource('setor', 'SectorController', ['as' => 'user']);
    Route::resource('funcao', 'OfficeController', ['as' => 'user']);
    Route::resource('unidade', 'UnityController', ['as' => 'user']);
    Route::resource('tipoitem', 'ItemTypeController', ['as' => 'user']);
    Route::resource('tipoentrada', 'EntranceTypeController', ['as' => 'user']);

    Route::get('/usuarios', 'UserController@index')->name('user.user.index');
    Route::post('/retirada/{id}/cancel', 'WithdrawalController@cancel')->name('user.retirada.cancel');
    Route::post('/retirada/{id}/approve', 'WithdrawalController@approve')->name('user.retirada.approve');
    Route::post('/retirada/{id}/giveback', 'WithdrawalController@giveback')->name('user.retirada.giveback');

    Route::get('/profile', 'UserController@profile')->name('user.profile');

    Route::get('/dashboard', 'DashboardController@index')->name('user.dashboard.index');
});

Route::post('/reportbug', 'ReportController@report')->name('reportbug');

app/Http/Controllers/Admin/ItemTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreItemType;
use App\Http\Requests\UpdateItemType;
use App\Models\ItemType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class ItemTypeController extends Controller
{/**
 * Display a listing of the resource.
 *
 * @return \Illuminate\Http\Response
 */
    public function index()
    {
        $itemTypes = ItemType::all();

        return view('admin.itemtype.index',compact('itemTypes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.itemtype.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreItemType $request)
    {
        $validated = $request->validated();

        $itemType = new ItemType($validated);
        $itemType->save();

        return redirect('/admin/tipoitem')->with('success', 'Nova tipo de item adicionado.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ItemType  $itemType
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $expiration = 60 * 60 *24;
        $key = 'itemtype_id_' . $id;

        $itemType = Cache::remember($key, $expiration, function () use ($id) {
            return ItemType::with([
                'tools.entrances.provider',
                'tools.entrances.warehouse',

                'tools.withdrawals.provider',
                'tools.withdrawals.warehouse',

                'tools.inventories',
                'tools.itemType',
                'tools.unity'
            ])->withTrashed()->find($id);
        });

        return view('admin.itemtype.show',compact('itemType'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ItemType  $itemType
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $expiration = 60 * 60 *24;
        $key = 'itemtype_id_' . $id;

        $itemType = Cache::remember($key, $expiration, function () use ($id) {
            return ItemType::with([
                'tools.entrances.provider',
                'tools.entrances.warehouse',

                'tools.withdrawals.provider',
                'tools.withdrawals.warehouse',

                'tools.inventories',
                'tools.itemType',
                'tools.unity'
            ])->withTrashed()->find($id);
        });

        return view('admin.itemtype.edit',compact('itemType'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ItemType  $itemType
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateItemType $request, $id)
    {
        $validated = $request->validated();

        $itemType = ItemType::find($id);
        //$itemType->doc = $request->get('doc');
        $itemType->name = $request->get('name');
        $itemType->save();

        return redirect('/admin/tipoitem')->with('success', 'Tipo de item editado.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ItemType  $itemType
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $itemType = ItemType::find($id);
        $itemType->delete();

        return redirect('/admin/tipoitem')->with('success', 'Tipo de item desativado.');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        $itemType = ItemType::withTrashed()->find($id);
        $itemType->restore();

        return redirect('/admin/tipoitem')->with('success', 'Tipo de item restaurado.');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function deleted()
    {
        $itemTypes = ItemType::onlyTrashed()->get();

        return view('admin.itemtype.deleted',compact('itemTypes'));
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Building;
use App\Models\Employee;
use App\Models\Office;
use App\Models\Role;
use App\Models\Sector;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    protected $expiration;
    protected $key;

    public function __construct()
    {
        $this->expiration = 60 * 60 * 24;
        $this->key = 'user';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $key = $this->key . '_all';
        $users = Cache::remember($key, $this->expiration, static function () {
            return User::with([
                    'employee',
                    'provider',
                    'role'
                ])->get();
        });

        return view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::withTrashed()->find($id);
        $employee = Employee::withTrashed()->find($user->employee['id']);
        $obras = Building::all();
        $sectors = Sector::all();
        $offices = Office::all();


        return view('admin.user.edit',compact('employee', 'obras', 'sectors', 'offices'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $user = User::find($id);

        if($request->get('access-level') < 4 or $request->get('access-level') == 5 ){
            // Update Email
            if($user->username != $request->get('username')) {
                $user->username = $request->get('username');
                $user->password = Hash::make($request->get('password'));
                $user->role = $request->get('access-level');

                $role = Role::where('role', $request->get('access-level'))->first();
                $role->user()->save($user);
            }

            // Update Password
            if($request->get('password') != null){
                $user->password = Hash::make($request->get('password'));
                $user->role = $request->get('access-level');

                $role = Role::where('role', $request->get('access-level'))->first();
                $role->user()->save($user);
            }
        }
        elseif($request->get('access-level') == 4){
            // Update Pin
            if($request->get('pin') != null){
                $user->pin = $request->get('pin');
                $user->role = $request->get('access-level');

                $role = Role::where('role', $request->get('access-level'))->first();
                $role->user()->save($user);
            }
        }

        // Update Level
        if($user->role != $request->get('access-level')) {
            $user->role = $request->get('access-level');

            $role = Role::where('role', $request->get('access-level'))->first();
            $role->user()->save($user);
        }

        return redirect('/admin/usuario')->with('success', 'Usuário de acesso editado.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/itemtype/index.blade.php
@extends('layouts.app')

@section('page-header')
    <div class="page-title">

        <div class="pull-left">
            <!-- PAGE HEADING TAG - START --><h1 class="title">Tipos</h1><!-- PAGE HEADING TAG - END -->                            </div>

        <div class="pull-right hidden-xs">
            <ol class="breadcrumb">
                <li>
                    <a href="/"><i class="fa fa-home"></i>Home</a>
                </li>
                <li class="active">
                    <strong>Tipos</strong>
                </li>
            </ol>
        </div>

    </div>
@endsection

@section('content')
    <div class="col-lg-12">
        <section class="box ">
            <header class="panel_header">
                <h2 class="title pull-left">Todos os Tipos</h2>
                <div class="actions panel_actions pull-right">
                    <a href="{{ route("admin.tipoitem.create") }}">
                        <button type="button" class="btn btn-primary btn-icon btn-sm">
                            <i class="fa fa-plus"></i> &nbsp; <span>Adicionar</span>
                        </button>
                    </a>
                </div>
            </header>
            <div class="content-body">
                <div class="row">
                    @if(session()->get('success'))
                        <div class="alert alert-success alert-dismissible fade in">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                            <strong>Sucesso!</strong> {{ session()->get('success') }}
                        </div>
                    @endif
                    <div class="col-xs-12">

                        <table class="table datatable display responsive no-wrap" width="100%">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Opções</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($itemTypes as $itemType)
                                <tr>
                                    <td>{{ $itemType->name }}</td>
                                    <td>
                                        <ul class="list-inline">
                                            <li>
                                                <a href="{{ route("admin.tipoitem.show", $itemType->id) }}">
                                                    <button class="btn btn-sm btn-info" title="Visualizar Tipo">
                                                        <span class="fa fa-eye"></span>
                                                    </button>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{{ route("admin.tipoitem.edit", $itemType->id) }}">
                                                    <button class="btn btn-sm btn-accent" title="Editar Tipo">
                                                        <span class="fa fa-edit"></span>
                                                    </button>
                                                </a>
                                            </li>
                                            <li>
                                                <form action="{{ route('admin.tipoitem.destroy', $itemType->id)}}" method="post">
                                                    @csrf
                                                    <meta name="_token" content="{{ csrf_token() }}">
                                                    @method('DELETE')
                                                    <button class="btn btn-sm btn-danger" title="Desativar Tipo"
                                                            data-toggle="confirm"
                                                            data-title=""
                                                            data-message="Tem certeza que deseja desativar esse tipo para itens?"
                                                            data-type="danger">
                                                        <span class="fa fa-trash"></span>
                                                    </button>
                                                </form>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@section('post_scripts')
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css"/>
    <script src="/assets/plugins/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/Responsive/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
    <script>
        $(document).ready( function () {
            $('.datatable').dataTable({
                responsive: true,
                "language": {
                    "url": "/assets/js/datatables-1.10.18/Portuguese-Brasil.json"
                }
            });
        } );
    </script>
@endsection

resources/views/user/itemtype/show.blade.php
@extends('layouts.app')

@section('page-header')
    <div class="page-title">

        <div class="pull-left">
            <!-- PAGE HEADING TAG - START --><h1 class="title">Tipos</h1><!-- PAGE HEADING TAG - END -->                            </div>

        <div class="pull-right hidden-xs">
            <ol class="breadcrumb">
                <li>
                    <a href="/"><i class="fa fa-home"></i>Home</a>
                </li>
                <li class="active">
                    <strong>Visualizar Tipo</strong>
                </li>
            </ol>
        </div>

    </div>
@endsection

@section('content')
    <div class="col-lg-12">
        <section class="box ">
            <header class="panel_header">
                <h2 class="title pull-left">Visualizar Tipo</h2>
                <div class="actions panel_actions pull-right">
                    <a class="box_toggle fa fa-chevron-down"></a>
                </div>
            </header>
            <div class="content-body">    <div class="row">
                    <div class="col-xs-12">

                        <div class="row">
                            <div class="col-md-4 col-sm-5 col-xs-10">

                                <div class="form-group">
                                    <label class="form-label" for="field-1">Nome</label>
                                    <div class="controls">
                                        <input type="text" class="form-control" name="name" value="{{ $itemType->name }}" readonly disabled >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="controls">
                                        <button class="btn btn-primary" onclick="history.back(-1)">Voltar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div class="col-lg-12">
        <section class="box ">
            <header class="panel_header">
                <h2 class="title pull-left">Visualizar Itens desse Tipo</h2>
                <div class="actions panel_actions pull-right">
                    <a class="box_toggle fa fa-chevron-down"></a>
                </div>
            </header>
            <div class="content-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="row">
                            <table class="table datatable display responsive no-wrap" width="100%">
                                <thead>
                                <tr>
                                    <th>Código da Item</th>
                                    <th>Descrição</th>
                                    <th>Tipo</th>
                                    <th>Unidade</th>
                                    <th>Quantidade Total</th>
                                    <th>Quantidade Retirada</th>
                                    <th>Saldo</th>
                                    <th>Opções</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($itemType->tools as $tool)
                                    <tr>
                                        <td>{{ $tool->cod }}</td>
                                        <td>{{ $tool->name }}</td>
                                        <td>{{ $tool->itemType['name'] }}</td>
                                        <td>{{ $tool->unity['name'] }}</td>
                                        <td>{{ $tool->inventories->sum('quantity') }} {{ $tool->unity['name'] }}(s)</td>
                                        <td>{{ $tool->withdrawals->sum('quantity') }} {{ $tool->unity['name'] }}(s)</td>
                                        <td>{{ $tool->inventories->sum('quantity') - $tool->withdrawals->sum('quantity') }} {{ $tool->unity['name'] }}(s)</td>
                                        <td>
                                            <ul class="list-inline">
                                                <li>
                                                    <a href="{{ route("admin.ferramenta.show", $tool->id) }}">
                                                        <button class="btn btn-sm btn-info" title="Visualizar Item">
                                                            <span class="fa fa-eye"></span>
                                                        </button>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="{{ route("admin.ferramenta.edit", $tool->id) }}">
                                                        <button class="btn btn-sm btn-accent" title="Editar Item">
                                                            <span class="fa fa-edit"></span>
                                                        </button>
                                                    </a>
                                                </li>
                                                <li>
                                                    <form action="{{ route('admin.ferramenta.destroy', $tool->id)}}" method="post">
                                                        @csrf
                                                        <meta name="_token" content="{{ csrf_token() }}">
                                                        @method('DELETE')
                                                        <button class="btn btn-sm btn-danger" title="Desativar Item"
                                                                data-toggle="confirm"
                                                                data-title=""
                                                                data-message="Tem certeza que deseja desativar essa ferramenta?"
                                                                data-type="danger">
                                                            <span class="fa fa-trash"></span>
                                                        </button>
                                                    </form>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@section('post_scripts')
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css"/>
    <script src="/assets/plugins/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/Responsive/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
    <script>
        $(document).ready( function () {
            $('.datatable').dataTable({
                responsive: true,
                "language": {
                    "url": "/assets/js/datatables-1.10.18/Portuguese-Brasil.json"
                }
            });
        } );
    </script>
@endsection