routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes(['register' => true]);

// Links Painel Admin
Route::group([
    'middleware' => 'auth',
    'prefix' => 'admin',
    'namespace' => 'Admin'], function() {

    // Listar Inativos
    Route::get('/almoxarifado/arquivado', 'WarehouseController@deleted')->name('admin.almoxarifado.deleted');
    Route::get('/fornecedor/arquivado', 'ProviderController@deleted')->name('admin.fornecedor.deleted');
    Route::get('/funcionario/arquivado', 'EmployeeController@deleted')->name('admin.funcionario.deleted');
    Route::get('/ferramenta/arquivado', 'ToolController@deleted')->name('admin.ferramenta.deleted');
    Route::get('/obra/arquivado', 'BuildingController@deleted')->name('admin.obra.deleted');
    Route::get('/setor/arquivado', 'SectorController@deleted')->name('admin.setor.deleted');
    Route::get('/funcao/arquivado', 'OfficeController@deleted')->name('admin.funcao.deleted');
    Route::get('/unidade/arquivado', 'UnityController@deleted')->name('admin.unidade.deleted');
    Route::get('/tipoitem/arquivado', 'ItemTypeController@deleted')->name('admin.tipoitem.deleted');
    Route::get('/tipoentrada/arquivado', 'ItemTypeController@deleted')->name('admin.tipoentrada.deleted');
    Route::get('/entrada/arquivado', 'EntranceController@deleted')->name('admin.entrada.deleted');
    Route::get('/retirada/arquivado', 'WithdrawalController@deleted')->name('admin.retirada.deleted');

    // Restaurar Inativos
    Route::post('/almoxarifado/restore/{id}', 'WarehouseController@restore')->name('admin.almoxarifado.restore');
    Route::post('/fornecedor/restore/{id}', 'ProviderController@restore')->name('admin.fornecedor.restore');
    Route::post('/funcionario/restore/{id}', 'EmployeeController@restore')->name('admin.funcionario.restore');
    Route::post('/ferramenta/restore/{id}', 'ToolController@restore')->name('admin.ferramenta.restore');
    Route::post('/obra/restore/{id}', 'BuildingController@restore')->name('admin.obra.restore');
    Route::post('/setor/restore/{id}', 'SectorController@restore')->name('admin.setor.restore');
    Route::post('/funcao/restore/{id}', 'OfficeController@restore')->name('admin.funcao.restore');
    Route::post('/unidade/restore/{id}', 'UnityController@restore')->name('admin.unidade.restore');
    Route::post('/tipoitem/restore/{id}', 'ItemTypeController@restore')->name('admin.tipoitem.restore');
    Route::post('/tipoentrada/restore/{id}', 'EntranceTypeController@restore')->name('admin.tipoentrada.restore');
    Route::post('/entrada/restore/{id}', 'EntranceController@restore')->name('admin.entrada.restore');
    Route::post('/retirada/restore/{id}', 'WithdrawalController@restore')->name('admin.retirada.restore');

    Route::get('/funcionario/usuario/{id}', 'EmployeeController@userEdit')->name('admin.funcionario.user.edit');
    Route::patch('/funcionario/usuario/{id}', 'EmployeeController@userUpdate')->name('admin.funcionario.user.update');

    // Resources
    Route::resource('fornecedor', 'ProviderController', ['as' => 'admin']);
    Route::resource('almoxarifado', 'WarehouseController', ['as' => 'admin']);
    Route::resource('funcionario', 'EmployeeController', ['as' => 'admin']);
    Route::resource('obra', 'BuildingController', ['as' => 'admin']);
    Route::resource('ferramenta', 'ToolController', ['as' => 'admin']);
    Route::resource('entrada', 'EntranceController', ['as' => 'admin']);
    Route::resource('retirada', 'WithdrawalController', ['as' => 'admin']);
    Route::resource('setor', 'SectorController', ['as' => 'admin']);
    Route::resource('funcao', 'OfficeController', ['as' => 'admin']);
    Route::resource('unidade', 'UnityController', ['as' => 'admin']);
    Route::resource('tipoitem', 'ItemTypeController', ['as' => 'admin']);
    Route::resource('tipoentrada', 'EntranceTypeController', ['as' => 'admin']);
    Route::resource('usuario', 'UserController', ['as' => 'admin']);
    Route::resource('fatura', 'InvoiceController', ['as' =>'admin']);
    Route::resource('transferencia', 'TransferController', ['as' =>'admin']);
    Route::resource('estoque', 'InventoryController', ['as' => 'admin']);


    Route::get('/usuarios', 'UserController@index')->name('admin.user.index');

    Route::get('/ferramentas/datatables.json', 'ToolController@datatablesAjax')->name('admin.ferramenta.datatables');

    Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard.index');

    Route::post('/transferencia/cancel/{id}', 'TransferController@cancel')->name('admin.transferencia.cancel');

    Route::post('/import/{type}', 'ImportController@import')->name('admin.import.submit');
});

Route::group([
    'middleware' => 'auth',
    'prefix' => 'user',
    'namespace' => 'User'], function() {

    // Listar Inativos
    Route::get('/almoxarifado/arquivado', 'WarehouseController@deleted')->name('user.almoxarifado.deleted');
    Route::get('/fornecedor/arquivado', 'ProviderController@deleted')->name('user.fornecedor.deleted');
    Route::get('/funcionario/arquivado', 'EmployeeController@deleted')->name('user.funcionario.deleted');
    Route::get('/ferramenta/arquivado', 'ToolController@deleted')->name('user.ferramenta.deleted');
    Route::get('/obra/arquivado', 'BuildingController@deleted')->name('user.obra.deleted');
    Route::get('/setor/arquivado', 'SectorController@deleted')->name('user.setor.deleted');
    Route::get('/funcao/arquivado', 'OfficeController@deleted')->name('user.funcao.deleted');
    Route::get('/unidade/arquivado', 'UnityController@deleted')->name('user.unidade.deleted');
    Route::get('/tipoitem/arquivado', 'ItemTypeController@deleted')->name('user.tipoitem.deleted');
    Route::get('/tipoentrada/arquivado', 'ItemTypeController@deleted')->name('user.tipoentrada.deleted');

    // Restaurar Inativos
    Route::post('/almoxarifado/restore/{id}', 'WarehouseController@restore')->name('user.almoxarifado.restore');
    Route::post('/fornecedor/restore/{id}', 'ProviderController@restore')->name('user.fornecedor.restore');
    Route::post('/funcionario/restore/{id}', 'EmployeeController@restore')->name('user.funcionario.restore');
    Route::post('/ferramenta/restore/{id}', 'ToolController@restore')->name('user.ferramenta.restore');
    Route::post('/obra/restore/{id}', 'BuildingController@restore')->name('user.obra.restore');
    Route::post('/setor/restore/{id}', 'SectorController@restore')->name('user.setor.restore');
    Route::post('/funcao/restore/{id}', 'OfficeController@restore')->name('user.funcao.restore');
    Route::post('/unidade/restore/{id}', 'UnityController@restore')->name('user.unidade.restore');
    Route::post('/tipoitem/restore/{id}', 'ItemTypeController@restore')->name('user.tipoitem.restore');
    Route::post('/tipoentrada/restore/{id}', 'EntranceTypeController@restore')->name('user.tipoentrada.restore');

    Route::get('/funcionario/usuario/{id}', 'EmployeeController@userEdit')->name('user.funcionario.user.edit');
    Route::patch('/funcionario/usuario/{id}', 'EmployeeController@userUpdate')->name('user.funcionario.user.update');

    // Resources
    Route::resource('fornecedor', 'ProviderController', ['as' => 'user']);
    Route::resource('almoxarifado', 'WarehouseController', ['as' => 'user']);
    Route::resource('funcionario', 'EmployeeController', ['as' => 'user']);
    Route::resource('obra', 'BuildingController', ['as' => 'user']);
    Route::resource('ferramenta', 'ToolController', ['as' => 'user']);
    Route::resource('entrada', 'EntranceController', ['as' => 'user']);
    Route::resource('retirada', 'WithdrawalController', ['as' => 'user']);
    Route::resource('setor', 'SectorController', ['as' => 'user']);
    Route::resource('funcao', 'OfficeController', ['as' => 'user']);
    Route::resource('unidade', 'UnityController', ['as' => 'user']);
    Route::resource('tipoitem', 'ItemTypeController', ['as' => 'user']);
    Route::resource('tipoentrada', 'EntranceTypeController', ['as' => 'user']);

    Route::get('/usuarios', 'UserController@index')->name('user.user.index');
    Route::post('/retirada/{id}/cancel', 'WithdrawalController@cancel')->name('user.retirada.cancel');
    Route::post('/retirada/{id}/approve', 'WithdrawalController@approve')->name('user.retirada.approve');
    Route::post('/retirada/{id}/giveback', 'WithdrawalController@giveback')->name('user.retirada.giveback');

    Route::get('/profile', 'UserController@profile')->name('user.profile');

    Route::get('/dashboard', 'DashboardController@index')->name('user.dashboard.index');
});

Route::post('/reportbug', 'ReportController@report')->name('reportbug');

app/Http/Controllers/Admin/ToolController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreTool;
use App\Http\Requests\UpdateTool;
use App\Models\ItemType;
use App\Models\Tool;
use App\Models\Unity;
use App\Repositories\ToolRepository;
use Freshbitsweb\Laratables\Laratables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class ToolController extends Controller
{
    protected $toolRepository;

    public function __construct()
    {
        $this->toolRepository = new ToolRepository();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tools = $this->toolRepository->all();

        /*
        foreach($tools as $tool){
            $tool->entrance_ids = [];
            $tool->withdrawal_ids = [];
            $tool->update();
        }
        */

        return view('admin.tool.index', compact('tools'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lastId = Tool::orderBy('created_at', 'desc')->first();
        $itenTypes = ItemType::all();
        $units = Unity::all();

        return view("admin.tool.create", compact('lastId','units', 'itenTypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTool $request)
    {
        $validated = $request->validated();

        $tool = $this->toolRepository->store($validated);

        return redirect('/admin/ferramenta')->with('success', 'Novo item adicionado.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tool = $this->toolRepository->find($id);

        return view('admin.tool.show',compact('tool'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tool = Tool::withTrashed()->find($id);
        $units = Unity::all();
        $itemTypes = ItemType::all();

        return view('admin.tool.edit',compact('tool', 'units', 'itemTypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTool $request, $id)
    {
        $validated = $request->validated();

        $tool = Tool::find($id);
        //$tool->minimum = $validated['minimun'];

        $unity = Unity::find($request->get('unity'));
        $unity->tools()->save($tool);

        $itemType = ItemType::find($request->get('type'));
        $itemType->tools()->save($tool);

        //$tool->update($validated);
        //dd($tool);

        return redirect('/admin/ferramenta')->with('success', 'Item editado.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tool = Tool::find($id);
        $tool->delete();

        return redirect('/admin/ferramenta')->with('success', 'Item deletado.');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        $tool = Tool::withTrashed()->find($id);
        $tool->restore();

        return redirect('/admin/ferramenta')->with('success', 'Item restaurada.');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function deleted()
    {
        $tools = Tool::onlyTrashed()->get();

        return view('admin.tool.deleted',compact('tools'));
    }

    public function datatablesAjax()
    {
        return Laratables::recordsOf(Tool::class, function()
        {
            return $this->toolRepository->datatables();
        });
    }
}

app/Http/Controllers/User/ToolController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Requests\StoreTool;
use App\Http\Requests\UpdateTool;
use App\Models\ItemType;
use App\Models\Tool;
use App\Models\Unity;
use App\Repositories\ToolRepository;
use Freshbitsweb\Laratables\Laratables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class ToolController extends Controller
{
    protected $toolRepository;

    public function __construct()
    {
        $this->toolRepository = new ToolRepository();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tools = $this->toolRepository->all();

        return view('user.tool.index', compact('tools'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lastId = Tool::orderBy('created_at', 'desc')->first();
        $itenTypes = ItemType::all();
        $units = Unity::all();

        return view("user.tool.create", compact('lastId','units', 'itenTypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTool $request)
    {
        $validated = $request->validated();

        $tool = new Tool($validated);

        $itemType = ItemType::find($request->input('type'));
        $itemType->tools()->save($tool);

        $unity = Unity::find($request->get('unity'));
        $unity->tools()->save($tool);

        return redirect('/user/ferramenta')->with('success', 'Novo item adicionado.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tool = $this->toolRepository->find($id);

        return view('user.tool.show',compact('tool'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $$tool = $this->toolRepository->find($id);
        $units = Unity::all();
        $itemTypes = ItemType::all();

        return view('user.tool.edit',compact('tool', 'units', 'itemTypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTool $request, $id)
    {
        $validated = $request->validated();

        $tool = $this->toolRepository->find($id);
        $tool->name = $request->get('name');

        $unity = Unity::find($request->get('unity'));
        $unity->tools()->save($tool);

        $itemType = ItemType::find($request->get('type'));
        $itemType->tools()->save($tool);

        //$tool->save();

        return redirect('/user/ferramenta')->with('success', 'Item editado.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tool = Tool::find($id);
        $tool->delete();

        return redirect('/user/ferramenta')->with('success', 'Item deletado.');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        $tool = Tool::withTrashed()->find($id);
        $tool->restore();

        return redirect('/user/ferramenta')->with('success', 'Item restaurada.');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function deleted()
    {
        $tools = Tool::onlyTrashed()->get();

        return view('user.tool.deleted',compact('tools'));
    }

    public function datatablesAjax()
    {
        return Laratables::recordsOf(Tool::class, function()
        {
            return $this->toolRepository->datatables();
        });
    }
}

resources/views/admin/tool/show.blade.php
@extends('layouts.app')

@section('page-header')
    <div class="page-title">

        <div class="pull-left">
            <!-- PAGE HEADING TAG - START --><h1 class="title">Ferramenta/Equipamento - {{ $tool->name }}</h1><!-- PAGE HEADING TAG - END -->                            </div>

        <div class="pull-right hidden-xs">
            <ol class="breadcrumb">
                <li>
                    <a href="/"><i class="fa fa-home"></i>Home</a>
                </li>
                <li>
                    <a href="#">Ferramenta/Equipamento</a>
                </li>
                <li class="active">
                    <strong>{{ $tool->name }}</strong>
                </li>
            </ol>
        </div>

    </div>
@endsection

@section('content')
    <div class="col-lg-12">
        <section class="box ">
            <header class="panel_header">
                <h2 class="title pull-left">Visualizar Item</h2>
                <div class="actions panel_actions pull-right">
                    <a class="box_toggle fa fa-chevron-down"></a>
                </div>
            </header>
            <div class="content-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-md-4 col-sm-5 col-xs-10">
                                <div class="form-group">
                                    <label class="form-label" for="field-1">Código do Item</label>
                                    <div class="controls">
                                        <input type="number" class="form-control" name="number" value="{{ $tool->cod }}" readonly disabled>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="form-label" for="field-1">Descrição</label>
                                    <div class="controls">
                                        <input type="text" class="form-control" name="name" value="{{ $tool->name }}" readonly disabled>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-5 col-xs-10">

                                <div class="form-group">
                                    <label class="form-label" for="field-1">Estoque Mínimo</label>
                                    <div class="controls">
                                        <input type="text" class="form-control" name="stock_min" value="{{ $tool['stock_min'] }} {{ $tool['unity']['name'] }}(s)" readonly disabled>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="form-label" for="field-1">Unidade</label>
                                    <div class="controls">
                                        <input type="text" class="form-control" name="quantity" value="{{ $tool['unity']['name'] }} ({{ $tool['unity']['symbol'] }})" readonly disabled>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4 col-sm-5 col-xs-10">

                                <div class="form-group">
                                    <label class="form-label" for="field-1">Tipo</label>
                                    <div class="controls">
                                        <input type="text" class="form-control" name="address" value="{{ $tool->itemType->name }}" readonly disabled>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>


    <div class="col-md-12">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#entrances" data-toggle="tab">
                    <i class="fa fa-plus"></i> Entradas
                </a>
            </li>
            <li>
                <a href="#withdrawals" data-toggle="tab">
                    <i class="fa fa-minus"></i> Retiradas
                </a>
            </li>
            <li>
                <a href="#warehouses" data-toggle="tab">
                    <i class="fa fa-warehouse"></i> Almoxarifados
                </a>
            </li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane fade in active" id="entrances">
                <table class="table datatable display responsive no-wrap" width="100%">
                    <thead>
                    <tr>
                        <th>Data de Entrada</th>
                        <th>Nº Nota Fiscal</th>
                        <th>CNPJ - Fornecedor</th>
                        <th>Almoxarifado</th>
                        <th>Opções</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($tool->entrances as $entrance)
                        <tr>
                            <td>{{ \Carbon\Carbon::parse($entrance->created_at)->format('d/m/Y')}}</td>
                            <td>{{ $entrance->doc }}</td>
                            <td>{{ $entrance->provider->doc }} - {{ $entrance->provider->name }}</td>
                            <td>{{ $entrance->warehouse->name }}</td>
                            <td>
                                <ul class="list-inline">
                                    <li>
                                        <a href="{{ route("admin.entrada.show", $entrance->id) }}">
                                            <button class="btn btn-sm btn-info" title="Visualizar Entrada">
                                                <span class="fa fa-eye"></span>
                                            </button>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="tab-pane fade" id="withdrawals">
                <table class="table datatable display responsive no-wrap" width="100%">
                    <thead>
                    <tr>
                        <th>Data de Retirada</th>
                        <th>Nº Nota Fiscal</th>
                        <th>CNPJ - Fornecedor</th>
                        <th>Funcionário</th>
                        <th>Almoxarifado</th>
                        <th>Obra</th>
                        <th>Opções</th>
                    </tr>
                    </thead>
                    <tbody>

                    @if($tool->withdrawals != '')
                        @foreach($tool->withdrawals as $withdrawal)
                            <tr>
                                <td>{{ \Carbon\Carbon::parse($withdrawal->created_at)->format('d/m/Y')}}</td>
                                <td>{{ $withdrawal->doc }}</td>
                                <td>
                                    @if(!empty($withdrawal->provider->id))
                                    <a href="{{ route("admin.fornecedor.show", $withdrawal->provider->id) }}">
                                        {{ $withdrawal->provider->doc }} - {{ $withdrawal->provider->name }}
                                    </a>
                                    @endif
                                </td>
                                <td>
                                    @if(!empty($withdrawal->employee->id))
                                    <a href="{{ route("admin.funcionario.show", $withdrawal->employee->id) }}">
                                        {{ $withdrawal->employee->name }}
                                    </a>
                                    @endif
                                </td>
                                <td>
                                </td>
                                <td>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li>
                                            <a href="{{ route("admin.retirada.show", $withdrawal->id) }}">
                                                <button class="btn btn-sm btn-info" title="Visualizar Retirada">
                                                    <span class="fa fa-eye"></span>
                                                </button>
                                            </a>
                                        </li>
                                        <li>
                                            <form action="{{ route('admin.retirada.destroy', $withdrawal->id)}}" method="post">
                                                @csrf
                                                <meta name="_token" content="{{ csrf_token() }}">
                                                @method('DELETE')
                                                <button class="btn btn-sm btn-danger" title="Desativar Retirada"
                                                        data-toggle="confirm"
                                                        data-title=""
                                                        data-message="Tem certeza que deseja desativar essa retirada?"
                                                        data-type="danger">
                                                    <span class="fa fa-trash"></span>
                                                </button>
                                            </form>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td>Sem retiradas</td>
                        </tr>
                    @endif
                    </tbody>
                </table>
            </div>
            <div class="tab-pane fade" id="warehouses">
                <table class="table datatable display responsive no-wrap" width="100%">
                    <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Obra</th>
                        <th>Estoque Mínimo</th>
                        <th>Quantidade Total em Estoque</th>
                        <th>Opções</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($tool->inventories as $inventory)
                        <tr>
                            <td>
                                <a href="{{ route('admin.almoxarifado.show', $inventory->warehouse->id) }}">
                                    {{ $inventory->warehouse->name }}
                                </a>
                            </td>
                            <td>
                                <a href="{{ route('admin.obra.show', $inventory->warehouse->building->id) }}">
                                    {{ $inventory->warehouse->building->name }}
                                </a>
                            </td>
                            <td>{{ $inventory['stock_min']}} {{ $inventory['tool']['unity']['name'] }}(s)</td>
                            <td>{{ $inventory['quantity'] }} {{ $inventory['tool']['unity']['name'] }}(s)</td>
                            <td>
                                <ul class="list-inline">
                                    <li>
                                        <a href="{{ route('admin.almoxarifado.show', $inventory->warehouse->id) }}">
                                            <button class="btn btn-sm btn-info" title="Visualizar Almoxarifado">
                                                <span class="fa fa-eye"></span>
                                            </button>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

    </div>

@endsection

@section('post_scripts')
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css"/>
    <script src="/assets/plugins/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/datatables/extensions/Responsive/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
    <script>
        $(document).ready( function () {
            $('.datatable').dataTable({
                responsive: true,
                lengthMenu: [
                    [ 10, 25, 50, 100, -1 ],
                    [ '10 linhas', '25 linhas', '50 linhas', '100 linhas', 'Mostrar Todos' ]
                ],
                "language": {
                    "url": "/assets/js/datatables-1.10.18/Portuguese-Brasil.json"
                }
            });
        } );
    </script>
@endsection